const topicsMap = new Map();
const peopleMap = new Map();

topicsMap.set("provoc", { name: "agent provocateurs", selected: false });
topicsMap.set("antifa", { name: "antifa", selected: false });
topicsMap.set("author", { name: "authoritarianism", selected: false });
topicsMap.set("blm", { name: "black lives matter", selected: false });
topicsMap.set("censor", { name: "censorship", selected: false });
topicsMap.set("banks", { name: "central banks", selected: false });
topicsMap.set("china", { name: "china", selected: false });
topicsMap.set("climate", { name: "climate change", selected: false });
topicsMap.set("covid", { name: "covid-19", selected: false });
topicsMap.set("crypto", { name: "crypto", selected: false });
topicsMap.set("demon", { name: "demonrats", selected: false });
topicsMap.set("elect", { name: "election fraud", selected: false });
topicsMap.set("elitist", { name: "elitist", selected: false });
topicsMap.set("energy", { name: "energy", selected: false });
topicsMap.set("eugen", { name: "eugenics", selected: false });
topicsMap.set("fnews", { name: "fake news", selected: false });
topicsMap.set("fflags", { name: "false flags", selected: false });
topicsMap.set("famine", { name: "famine", selected: false });
topicsMap.set("food", { name: "food supply", selected: false });
topicsMap.set("speech", { name: "free speech", selected: false });
topicsMap.set("geno", { name: "genocide", selected: false });
topicsMap.set("glob", { name: "globalists", selected: false });
topicsMap.set("greset", { name: "great reset", selected: false });
topicsMap.set("gthink", { name: "groupthink", selected: false });
topicsMap.set("guns", { name: "gun rights", selected: false });
topicsMap.set("hero", { name: "hero", selected: false });
topicsMap.set("htraf", { name: "human trafficking", selected: false });
topicsMap.set("immig", { name: "immigration", selected: false });
topicsMap.set("infla", { name: "inflation", selected: false });
topicsMap.set("matrix", { name: "the matrix", selected: false });
topicsMap.set("msurv", { name: "mass surveillance", selected: false });
topicsMap.set("nano", { name: "nanotech", selected: false });
topicsMap.set("nwo", { name: "new world order", selected: false });
topicsMap.set("pland", { name: "plandemics", selected: false });
topicsMap.set("popctrl", { name: "population control", selected: false });
topicsMap.set("priv", { name: "privacy", selected: false });
topicsMap.set("prop", { name: "propaganda", selected: false });
topicsMap.set("protest", { name: "protest", selected: false });
topicsMap.set("race", { name: "racism", selected: false });
topicsMap.set("rewrite", { name: "rewrite history", selected: false });
topicsMap.set("satan", { name: "satanism", selected: false });
topicsMap.set("scredit", { name: "social credit scores", selected: false });
topicsMap.set("smedia", { name: "social media", selected: false });
topicsMap.set("schain", { name: "supply chain", selected: false });
topicsMap.set("tctrl", { name: "thought control", selected: false });
topicsMap.set("thuman", { name: "transhumanism", selected: false });
topicsMap.set("vax", { name: "vaccines", selected: false });
topicsMap.set("war", { name: "war", selected: false });
topicsMap.set("woke", { name: "wokeness", selected: false });
topicsMap.set("wef", { name: "world economic forum", selected: false });
topicsMap.set("who", { name: "world health organization", selected: false });
peopleMap.set("ahitler", { name: "adolf hitler", selected: false });
peopleMap.set("abourla", { name: "albert bourla", selected: false });
peopleMap.set("ajones", { name: "alex jones", selected: false });
peopleMap.set("aocortez", {
  name: "alexandria ocasio-cortez",
  selected: false
});
peopleMap.set("bclinton", { name: "bill clinton", selected: false });
peopleMap.set("bgates", { name: "bill gates", selected: false });
peopleMap.set("cschumer", { name: "chuck schumer", selected: false });
peopleMap.set("dtrump", { name: "donald trump", selected: false });
peopleMap.set("gnewsom", { name: "gavin newsom", selected: false });
peopleMap.set("gsoros", { name: "george soros", selected: false });
peopleMap.set("gwhitmer", { name: "gretchen whitmer", selected: false });
peopleMap.set("jbezos", { name: "jeff bezos", selected: false });
peopleMap.set("jepstein", { name: "jeffrey epstein", selected: false });
peopleMap.set("jpowell", { name: "jerome powell", selected: false });
peopleMap.set("jbiden", { name: "joe biden", selected: false });
peopleMap.set("jrogan", { name: "joe rogan", selected: false });
peopleMap.set("jtrudeau", { name: "justin trudeau", selected: false });
peopleMap.set("hclinton", { name: "hillary clinton", selected: false });
peopleMap.set("kharris", { name: "kamala harris", selected: false });
peopleMap.set("kschwab", { name: "klaus schwab", selected: false });
peopleMap.set("llightfoot", { name: "lori lightfoot", selected: false });
peopleMap.set("mzuckerberg", { name: "mark zuckerberg", selected: false });
peopleMap.set("npelosi", { name: "nancy pelosi", selected: false });
peopleMap.set("rmalone", { name: "robert malone", selected: false });
peopleMap.set("sbf", { name: "sam bankman-fried", selected: false });
peopleMap.set("tfauci", { name: "tony fauci", selected: false });
peopleMap.set("tcarlson", { name: "tucker carlson", selected: false });
peopleMap.set("vputin", { name: "vladimir putin", selected: false });
peopleMap.set("xjinping", { name: "xi jinping", selected: false });
peopleMap.set("yharari", { name: "yuval noah harari", selected: false });

export { topicsMap, peopleMap };
